drop table if exists users;

/*
    {
        "firstName": "Frank",
        "lastName": "Murphy",
        "email": "frank.murphy@rustvale.com",
        "role": "User",
        "password": "sue123",
        "title": "Mr",
        "id": 1,
        "dateCreated": "2021-04-08T05:33:05.184Z",
        "dateUpdated": "2021-04-08T05:33:05.184Z"
    },
 */

create table users (
    id          bigint generated by default as identity,
    first_name  varchar(100) not null,
    last_name   varchar(100) not null,
    email       varchar(100) not null,
    role        varchar(10)  not null,
    password    varchar(255) not null,
    title       varchar(20),
    create_dts  timestamp    not null default CURRENT_TIMESTAMP,
    update_dts  timestamp,
    primary key (id)
);
